# Generated by Django 5.0.4 on 2024-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('phones', 'Phones'), ('laptops', 'Laptops'), ('drones', 'Drones'), ('cameras', 'Cameras'), ('camera_stands', 'Camera Stands'), ('lenses', 'Lenses'), ('microphone', 'Microphone'), ('other', 'other')], max_length=70)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('rrp_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_image_thumbnails')),
                ('release_date', models.DateField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
